INSERT INTO ROOM(ROOM_ID) VALUES(1);
INSERT INTO ROOM(ROOM_ID) VALUES(2);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', 2);

INSERT INTO NOISE(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 80, 'ON', 1);
INSERT INTO NOISE(ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 20, 'OFF', 2);