INSERT INTO BUILDING(ID, NAME) VALUES(1, 'Espace Fauriel');
INSERT INTO BUILDING(ID, NAME) VALUES(2, 'Cours Fauriel');

INSERT INTO ROOM(ID, NAME, FLOOR,BUILDING_ID) VALUES(-10, 'Room1', 1,1);
INSERT INTO ROOM(ID, NAME, FLOOR,BUILDING_ID) VALUES(-9, 'Room2', 1,2);

INSERT INTO LIGHT(ID,BRIGHTNESS,HUE, STATUS, ROOM_ID) VALUES (-1,300,100, 'ON', -10);
INSERT INTO LIGHT(ID,BRIGHTNESS,HUE, STATUS, ROOM_ID) VALUES (-2, 200,40,'OFF', -10);